spring.application.name=productservice
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/productdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=product-exchange
app.rabbitmq.routing-key=product-routing-key

logging.level.root=INFO
logging.level.com.example.productservice=DEBUG